app_version: mongodb-1.1.38
capabilities: []
categories:
- management
description: Freely manage your devices
home: https://meshcentral.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/meshcentral/icons/icon.png
keywords:
- vpro
- amt
- remote-control
lib_version: 2.1.14
lib_version_hash: 982057eeec3024ccecbeaa70e9ee59d948523a3b29d9fca6b39f127a42caa1cc
maintainers:
- email: brian@grumbleranch.com
  name: Brian Iverson
  url: https://github.com/grumblebrian/
name: meshcentral
run_as_context:
- description: MeshCentral runs as any non-root user.
  gid: 2086
  group_name: meshcentral
  uid: 2086
  user_name: meshcentral
screenshots:
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot3.png
sources:
- https://github.com/Ylianst/MeshCentral
- https://github.com/Typhonragewind/meshcentral-docker
title: MeshCentral
train: stable
version: 1.1.38
